# Generated by Django 4.0.4 on 2022-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginApp',
            new_name='RKIPSLI',
        ),
    ]
