# Generated by Django 4.0.4 on 2022-06-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclweb', '0002_rename_loginapp_rkipsli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rkipsli',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='rkipsli',
            old_name='username',
            new_name='username1',
        ),
    ]
