# Generated by Django 4.0.4 on 2022-06-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclweb', '0003_rename_password_rkipsli_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rkipsli',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='rkipsli',
            old_name='username1',
            new_name='username',
        ),
    ]
