# Generated by Django 4.0.4 on 2022-06-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sclweb', '0004_rename_password1_rkipsli_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rkipsli',
            old_name='password',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='rkipsli',
            old_name='username',
            new_name='Name',
        ),
    ]
